package com.example.filmapp.services

object ConstService {
    const val DETAILS_INTENT_FILTER = "DETAILS INTENT FILTER"
    const val DETAILS_LOAD_RESULT_EXTRA = "LOAD RESULT"
    const val DETAILS_REQUEST_ERROR_EXTRA = "REQUEST ERROR"
    const val DETAILS_REQUEST_ERROR_MESSAGE_EXTRA = "REQUEST ERROR MESSAGE"
    const val DETAILS_URL_MALFORMED_EXTRA = "URL MALFORMED"
    const val DETAILS_RESPONSE_SUCCESS_EXTRA = "RESPONSE SUCCESS"
    const val DETAILS_TEMP_EXTRA = "TEMPERATURE"
}